### ISSUE TITLE
Problem with heads

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#14] opened 2021-02-08 15:51 UTC
Player heads in guis are bugged

**Comment by DeadSteve51** [comment] 2021-02-21 23:52
Dont use nacho it isn't stable

**Comment by assasin541** [comment] 2021-02-22 00:46
@DeadSteve51 what do you recommend to use?

**Comment by CyberFlameGO** [comment] 2021-04-24 13:24
I think @Lucaskyy fixed this, @HeathLoganCampbell you’re good to close this

**Comment by andreasdc** [comment] 2021-04-24 15:16
@CyberFlameGO I didn't find proper fix for this issue.

**Comment by CyberFlameGO** [comment] 2021-04-24 23:56
@andreasdc We merged Lucas’ fork to upstream, and if I’m not mistaken, it’s fixed in that fork. Please let me know if it isn’t :)

**Comment by andreasdc** [comment] 2021-04-25 00:01
@CyberFlameGO I don't see any fix to this bug.

**Comment by CyberFlameGO** [comment] 2021-04-25 00:20
I think it’s this? `[SportPaper-0027] Fix head rotation packet spam`
I could be wrong though (in that it’s not fixed)

**Comment by andreasdc** [comment] 2021-04-25 00:21
@CyberFlameGO then it's not fixed. When you have guis with player heads (setOwner) it appears as the same skin/head.

**Comment by Lucaskyy** [comment] 2021-04-25 00:22
Ah no, that is not the fix for that. I will try to reproduce this soon and get a fix for it.

**Comment by Lucaskyy** [comment] 2021-04-25 00:23
@andreasdc "with the same skin/head" you mean Steve/Alex skin?

**Comment by andreasdc** [comment] 2021-04-25 00:27
@Lucaskyy it gets first shown player head, but it doesn't happen in all types of guis.

**Comment by andreasdc** [comment] 2021-04-25 00:28
@Lucaskyy maybe it's because I don't create new SkullMeta for this type of gui, but I use old one and change displayname and owner?

**Comment by Lucaskyy** [comment] 2021-04-25 00:32
Create a new SkullMeta and set it to the ItemStack. Don't reuse it.

Try this :)

**Comment by andreasdc** [comment] 2021-04-25 00:40
@Lucaskyy I will try that today. :) It worked on taco etc. before.

**Comment by andreasdc** [comment] 2021-04-25 00:43
@Lucaskyy btw. good job on updating, you can look on other issues and look for improvements from other projects too. Keep up the good work! 🥇 ❤️

**Comment by Lucaskyy** [comment] 2021-04-25 00:44
> @Lucaskyy btw. good job on updating, you can look on other issues and look for improvements from other projects too. Keep up the good work! 🥇 ❤️ 

Thank you! :) And yes, I will.

**Comment by DeadSteve51** [comment] 2021-04-25 00:44
Nacho comeback?

**Comment by DeadSteve51** [comment] 2021-04-25 00:44
Someone should close this

**Comment by CyberFlameGO** [comment] 2021-04-25 00:45
Turns out this doesn’t need closing yet :)

**Comment by Lucaskyy** [comment] 2021-04-25 00:45
By the way, if you can;

Could you send me your code that is having issues with NachoSpigot so I can try it out locally.

**Comment by andreasdc** [comment] 2021-04-25 00:48
@Lucaskyy can you give me the discord?

**Comment by CyberFlameGO** [comment] 2021-04-25 00:49
Take a look at the README.md on this repository, it’s there already

**Comment by Lucaskyy** [comment] 2021-04-25 13:46
This seems to be more of a plugin issue than a NachoSpigot issue.

Re-using ItemStacks doesn't seem to work when using SkullMeta's. Is that normal MC behavior?

Please re-open this issue if you know what the issue could be behind this!

**Closed by Lucaskyy** 2021-04-25 13:46 UTC

**Comment by Lucaskyy** [comment] 2021-04-28 07:40
After some time taking a look, I noticed that this seems to be a Spigot or TacoSpigot issue. They have modified the TileEntitySkull and made some changes, which means I can't really go back to that since I don't have the old source code to see what got changed. My best bet for now is, don't reuse the ItemStacks when using SkullMeta's.

When I get some time, I might take a look at this to fix it.

**Comment by Lucaskyy** [comment] 2021-07-22 14:19
Wanted to note, that if I recall correctly this issue has been fixed a couple weeks ago. So please try again using the latest version!

**Comment by andreasdc** [comment] 2021-07-22 14:49
> Wanted to note, that if I recall correctly this issue has been fixed a couple weeks ago. So please try again using the latest version!

It's kind of fixed yes. :)
