### ISSUE TITLE
Crash/error when unloading chunks

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#240] opened 2021-11-14 12:25 UTC
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:589) ~[fastutil-core-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.LongIterator.next(LongIterator.java:43) ~[fastutil-core-8.5.6.jar:?]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:406) ~[spigot.jar:?]

**Comment by sadcenter** [comment] 2021-11-14 12:29
Ummm, Is this the full error?

**Comment by andreasdc** [comment] 2021-11-14 12:38
Why do you need more?
Error is on this line: 
long chunkcoordinates = iterator.next();
Started happening after last patch

**Comment by tomasalves8** [comment] 2021-11-14 12:39
When does this happen?

**Comment by Elierrr** [comment] 2021-11-14 12:43
Seems to be caused by https://github.com/CobbleSword/NachoSpigot/commit/eeb6efd979e8d30b18ec200638672e3064e2b80c#diff-a356bfe365a4c958ad537841328b60039f88636200936515cf7a68310b726fd8



> When does this happen?

When chunks are unloaded

**Comment by tomasalves8** [comment] 2021-11-14 12:44
Can't reproduce, are you in the overworld? Do you have autosave turned on/off?

**Comment by andreasdc** [comment] 2021-11-14 12:46
> Can't reproduce, are you in the overworld? Do you have autosave turned on/off?

No main world, autosave off.

**Comment by tomasalves8** [comment] 2021-11-14 12:53
`at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:406) ~[spigot.jar:?]`

Line 406 is a comment, have you made any changes to the code?

**Comment by andreasdc** [comment] 2021-11-14 12:54
> Error is on this line:
> long chunkcoordinates = iterator.next();

@tomasalves8

**Comment by tomasalves8** [comment] 2021-11-14 12:54
That is line 411.

**Comment by andreasdc** [comment] 2021-11-14 12:55
> Why do you need more? Error is on this line: long chunkcoordinates = iterator.next(); Started happening after last patch

@tomasalves8

**Comment by tomasalves8** [comment] 2021-11-14 12:57
Like I said before that is line 411, but the stacktrace is indicating line 406, **Have you made any changes to the code? **

**Comment by Elierrr** [comment] 2021-11-14 13:01
> Like I said before that is line 411, but the stacktrace is indicating line 406, **Have you made any changes to the code?**

The code has comments before line 406 so the stacktrace won't have the correct line.

**Comment by andreasdc** [comment] 2021-11-14 13:51
> Like I said before that is line 411, but the stacktrace is indicating line 406, **Have you made any changes to the code?**

Yea

**Comment by tomasalves8** [comment] 2021-11-14 15:44
What changes have you made?

**Comment by Lucaskyy** [comment] 2021-11-14 15:49
He hasn't I think. @andreasdc could you test something for me?

**Comment by Lucaskyy** [comment] 2021-11-14 15:50
Try downloading this build here, once it's done: https://github.com/CobbleSword/NachoSpigot/actions/runs/1459216892
Then check if you get the same error again.

**Comment by andreasdc** [comment] 2021-11-14 17:55
> He hasn't I think. @andreasdc could you test something for me?

I made many changes, I will test nextLong and I will tell you the results. :)

**Comment by andreasdc** [comment] 2021-11-15 15:44
Still happening. @Lucaskyy

**Comment by andreasdc** [comment] 2021-11-15 15:45
@tomasalves8

**Comment by Rastrian** [comment] 2021-11-16 08:46
How we can reproduce this error? We didn't know about which kind of changes made locally.

**Comment by andreasdc** [comment] 2021-11-16 08:47
> How we can reproduce this error? We didn't know about which kind of changes made locally.

Try with multiple worlds

**Comment by Rastrian** [comment] 2021-11-16 08:50
> > How we can reproduce this error? We didn't know about which kind of changes made locally.
> 
> Try with multiple worlds

nah, just won't fix it without an detailed error report.

**Comment by andreasdc** [comment] 2021-11-16 08:51
> > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > 
> > 
> > Try with multiple worlds
> 
> nah, just won't fix it without an detailed error report.

What is missing in the error and why do you need more?

**Comment by Rastrian** [comment] 2021-11-16 08:58
> > > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > > 
> > > 
> > > Try with multiple worlds
> > 
> > nah, just won't fix it without an detailed error report.
> 
> What is missing in the error and why do you need more?

At the point where I can't reproduce the reported error, it can simply be derived from its implementation in your code. 

Have you tested this with other multi-world plugins besides your proprietary implementation? 

Because as said, it may be your mistake, without enough details there is no way to know and correct it.

**Comment by andreasdc** [comment] 2021-11-16 09:42
> > > > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > > > 
> > > > 
> > > > Try with multiple worlds
> > > 
> > > 
> > > nah, just won't fix it without an detailed error report.
> > 
> > 
> > What is missing in the error and why do you need more?
> 
> At the point where I can't reproduce the reported error, it can simply be derived from its implementation in your code.
> 
> Have you tested this with other multi-world plugins besides your proprietary implementation?
> 
> Because as said, it may be your mistake, without enough details there is no way to know and correct it.

It doesn't happen instantly,if you need more info or some other checks I can help.

**Comment by Rastrian** [comment] 2021-11-16 12:43
> > > > > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > > > > 
> > > > > 
> > > > > Try with multiple worlds
> > > > 
> > > > 
> > > > nah, just won't fix it without an detailed error report.
> > > 
> > > 
> > > What is missing in the error and why do you need more?
> > 
> > 
> > At the point where I can't reproduce the reported error, it can simply be derived from its implementation in your code.
> > Have you tested this with other multi-world plugins besides your proprietary implementation?
> > Because as said, it may be your mistake, without enough details there is no way to know and correct it.
> 
> It doesn't happen instantly,if you need more info or some other checks I can help.

that's why a full report matters.

**Comment by tomasalves8** [comment] 2021-11-16 12:47
> 
> 
> > > > > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > > > > 
> > > > > 
> > > > > Try with multiple worlds
> > > > 
> > > > 
> > > > nah, just won't fix it without an detailed error report.
> > > 
> > > 
> > > What is missing in the error and why do you need more?
> > 
> > 
> > At the point where I can't reproduce the reported error, it can simply be derived from its implementation in your code.
> > Have you tested this with other multi-world plugins besides your proprietary implementation?
> > Because as said, it may be your mistake, without enough details there is no way to know and correct it.
> 
> It doesn't happen instantly,if you need more info or some other checks I can help.

I've tried pretty much everything, in save-on and off.
- Multiple Dimensions
- Multiple Worlds
- 2 computers
- I've waited and reloaded the worlds several times
- Moved around, and tped random coords

**Comment by Rastrian** [comment] 2021-11-16 12:49
@Lucaskyy close this issue, if we want an fix for this, please submit another issue, the issue template now demands an detailed report.

**Comment by Lucaskyy** [comment] 2021-11-16 12:57
@andreasdc Closing this issue for now, please create a new issue with the new issue templates.

**Closed by Lucaskyy** 2021-11-16 12:57 UTC

**Comment by andreasdc** [comment] 2021-11-16 13:03
> > > > > How we can reproduce this error? We didn't know about which kind of changes made locally.
> > > > 
> > > > 
> > > > Try with multiple worlds
> > > 
> > > 
> > > nah, just won't fix it without an detailed error report.
> > 
> > 
> > What is missing in the error and why do you need more?
> 
> At the point where I can't reproduce the reported error, it can simply be derived from its implementation in your code.
> 
> Have you tested this with other multi-world plugins besides your proprietary implementation?
> 
> Because as said, it may be your mistake, without enough details there is no way to know and correct it.

I don't think that's my mistake.

**Comment by Lucaskyy** [comment] 2021-11-16 13:16
It's difficult to tell that since you're using a private fork of yours. We don't know your code, and nor do we know what changes you made. And since it doesn't happen on NachoSpigot, we can only guess that it's your mistake. Could you switch your private fork with NachoSpigot (keep the rest the same) and try again and see if it happens? Because if not, then it's definitely your mistake. And since we also don't know your exact environment, we can't exactly reproduce it. So that's why I told you to create an issue using the issue template, and use NachoSpigot to test this bug instead of your fork. We can't and don't support forks of NachoSpigot.

**Comment by andreasdc** [comment] 2021-11-16 15:05
> It's difficult to tell that since you're using a private fork of yours. We don't know your code, and nor do we know what changes you made. And since it doesn't happen on NachoSpigot (for what we know), we can only guess that it's your mistake. Could you switch your private fork with NachoSpigot (keep the rest the same) and try again and see if it happens? Because if not, then it's definitely your mistake. And since we also don't know your exact environment, we can't exactly reproduce it. So that's why I told you to create an issue using the issue template, and use NachoSpigot to test this bug instead of your fork. We can't and don't support forks of NachoSpigot.

If it was my mistake that would only be indicated by async call to unloadQueue, I don't find anything like that.
