### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Sxhqil** [CobbleSword/NachoSpigot#292] opened 2021-12-13 07:33 UTC
### Observed Behavior

I just cloned the project with git and opened it in IntelliJ and just did mvn clean install but i got an Error:

``Invalid artifact dependency name, must be groupId:artifactId:version:type:classifier C:\Users\Sohqil RF\Desktop\Build Tools\NachoSpigot\NachoSpigot-Server/deprecation-mappings.csrg in 2``

![image](https://user-images.githubusercontent.com/95770249/145770364-6c3172bb-444a-4624-a0ce-8aa1511fcf3b.png)

I didn't change anything

### Expected Behavior

.

### Steps To Reproduce

1. Clone the NachoSpigot with Git
2. Open the project by IntelliJ
3. Do mvn clean install in maven

### Server Version

1.8.8 latest, I downloaded today

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment] 2021-12-13 09:38
Duplicate of #288.

**Closed by Lucaskyy** 2021-12-13 09:38 UTC
Labels: bug

**Comment by Lucaskyy** [comment] 2021-12-13 09:40
You had 2 issues, issue 288 and this one ^
So it's not a duplicate, but the issue is invalid since this is not a compilation error but IntelliJ not understanding something.
