### ISSUE TITLE
Single water bucket placement causes 4 block change updates

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#277] opened 2021-12-06 05:02 UTC
### Observed Behavior

As in the description.
2 block changes from here:
https://github.com/CobbleSword/NachoSpigot/blob/da83aa42f12619e9b6c2ebf5cc366fd7540f7cb1/NachoSpigot-Server/src/main/java/net/minecraft/server/PlayerConnection.java#L928
and 2 block changes from here:
https://github.com/CobbleSword/NachoSpigot/blob/da83aa42f12619e9b6c2ebf5cc366fd7540f7cb1/NachoSpigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java#L485
(from here only 1 packet is sent when water is taken, not placed)
### Expected Behavior

Only 1 block change should happen.

### Steps To Reproduce

Place water of bucket or try to remove one from the ground.

### Server Version

-

### Other

While 2 block updates from PlayerConnection is an easy fix, I don't think these 2 block updates from PlayerChunkMap should happen.

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by LewUwU** [comment] 2021-12-06 09:56
Don't do issues without having a bit of testing of the requested changes

**Comment by Lucaskyy** [comment] 2021-12-06 12:11
Wait a second, so you're ticking the checkmark saying you're using NachoSpigot but you didn't provide the /version output? Could you please provide the output of the /version command and edit your issue comment?

**Comment by Elierrr** [comment] 2021-12-06 12:24
When I was testing #204 this happened with any block. Also I believe this is vanilla behavior.

**Comment by LewUwU** [comment] 2021-12-06 18:08
> > Don't do issues without having a bit of testing of the requested changes
> 
> I can't test it if it's not done yet.
> 
> > Wait a second, so you're ticking the checkmark saying you're using NachoSpigot but you didn't provide the /version output? Could you please provide the output of the /version command and edit your issue comment?
> 
> I don't know how would that help as it will only show the newest version of Nacho, but yea, let me know if you still want it.
> 
> > When I was testing #204 this happened with any block. Also I believe this is vanilla behavior.
> 
> I think when placing normal blocks only 1 packet was being sent.

Also you marked this as a bug without knowing if the original purpose was this

**Comment by andreasdc** [comment] 2021-12-06 18:09
> s

You want to send 4 block updates when 1 block is changing? Ok you can close the issue then.

**Comment by LewUwU** [comment] 2021-12-06 18:10
> > s
> 
> You want to send 4 block updates when 1 block is changing? Ok you can close the issue then.

Instead of being a asshole, you can read my whole comment
(Sorry for the word BUT USE YOUR BRAIN)

**Comment by andreasdc** [comment] 2021-12-06 18:11
"Also you marked this as a bug without knowing if the original purpose was this

Write it in proper english and apologise.

**Comment by LewUwU** [comment] 2021-12-06 18:13
> "Also you marked this as a bug without knowing if the original purpose was this
> 
> Write it in proper english and apologise.

Be my teacher please, and don't change the conversation

**Comment by Lucaskyy** [comment] 2021-12-06 18:22
Don't act so childish, jesus christ..
I've had enough of this.

**Closed** 2021-12-06 18:37 UTC
Labels: bug

**Comment by Lucaskyy** [comment] 2021-12-06 18:40
The reason I closed this is that it is intended behavior. This block update is there in ALL versions of Paper and no one has ever done anything about it. Paper definitely has better developers that notice these things, and they either missed this, which is unlikely, or they left it there since it is intended, which is more of the side I'm moving towards.
