### ISSUE TITLE
Error with packetevents 2.0

### ISSUE THREAD

**Issue by zhusun890** [CobbleSword/NachoSpigot#400] opened 2022-04-06 07:56 UTC
### Observed Behavior

When packetevents 2.0 receives and processing a packet, player will be kicked from the game on pre-login state for "Exception Connecting: NativeIOException : readAddress(...) failed: Connection reset by peer"

### Expected Behavior

Add a plugin patch for packetevents 2.0

### Steps To Reproduce

1. Open a FlameCord server and a NachoSpigot server
2. Connect to the NachoSpigot server from FlameCord server
3. Player has force disconnect and Error logs appears in console.

### Plugin List

Only PacketEvents 2.0

### Server Version

NachoSpigot 1.8.8 latest build. (Checked)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by Lucaskyy** [comment] 2022-04-06 11:51
Can you try removing PacketEvents? Does the issue still occur?

**Comment by Elierrr** [comment] 2022-04-07 16:05
> Can you try removing PacketEvents? Does the issue still occur?

Another similar issue with PacketEvents was reported in the discord. Errors logs are at https://bin.studiobeam.xyz/sekogonaxe.swift

**Comment by retrooper** [comment] 2022-04-08 21:33
Resolved, duplicate of https://github.com/CobbleSword/NachoSpigot/issues/356

**Comment by Lucaskyy** [comment] 2022-04-08 22:26
Duplicate of #356

**Closed by Lucaskyy** 2022-04-08 22:26 UTC
Labels: bug
