### ISSUE TITLE
I can't Join my server

### ISSUE THREAD

**Issue by Fumio-26** [CobbleSword/NachoSpigot#367] opened 2022-03-02 15:42 UTC
### Observed Behavior

 Nothing

### Expected Behavior

Nothing

### Steps To Reproduce

Nothing

### Plugin List

Plugins (23): FastAsyncWorldEdit, Skript, SkBee, HideItem, MundoSK, SlimeWorldManager, PlaceholderAPI, DisableJoinMessage, ViaVersion, ProtocolLib, LuckPerms, Skellett, WorldEdit, skRayFall, Vulcan, Images, Vault, Essentials, EssentialsProtect, EssentialsChat, TAB, AdvancedBan, EssentialsSpawn

### Server Version

This server is running NachoSpigot version git-NachoSpigot-unknown (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT) Unknown version

### Other

/172.18.0.1:46554
![image](https://user-images.githubusercontent.com/89429493/156395646-189eabfa-7201-49b0-810e-dfc7d73a75c9.png)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by Fumio-26** [comment] 2022-03-02 15:43
im using bungeecord/xcord

**Comment by HowardZHY** [comment] 2022-03-02 15:44
Unknown nacho ver ?

**Comment by LewUwU** [comment] 2022-03-02 20:01
BungeeCord side log please?

**Comment by Lucaskyy** [comment] 2022-03-02 20:53
This looks like a BungeeCord issue, please look into that first.
Also, are you using a custom fork of NachoSpigot? If so, please note we generally don't support that since we don't know if it was caused by your own changes. If you find an issue, please check if that also happens on the latest downloadable version of NachoSpigot. If so, please report the bug, if not please don't report the bug and fix it on your end.

I am going to close this issue right now since it's invalid, if the issue continues please reopen this issue and give more information as specified above.

**Closed by Lucaskyy** 2022-03-02 20:53 UTC
Labels: bug

**Comment by Fumio-26** [comment] 2022-03-03 00:49
![image](https://user-images.githubusercontent.com/89429493/156474696-527b5bea-543b-4e01-b76d-3a7a002f1725.png)
Im using "original-NachoSpigot"

**Comment by Fumio-26** [comment] 2022-03-03 00:56
Magic! Work im using "original-NachoSpigot"
lol

**Comment by HowardZHY** [comment] 2022-03-03 04:10
Is there anyone knows what's that build?

**Comment by Lucaskyy** [comment] 2022-03-03 10:43
That's the name of the JAR, not the version.

**Comment by LewUwU** [comment] 2022-03-03 20:26
> ![image](https://user-images.githubusercontent.com/89429493/156474696-527b5bea-543b-4e01-b76d-3a7a002f1725.png) Im using "original-NachoSpigot"

you should use the -remapped version so you don't get metrics errors

**Comment by Elierrr** [comment] 2022-03-03 20:53
> > ![image](https://user-images.githubusercontent.com/89429493/156474696-527b5bea-543b-4e01-b76d-3a7a002f1725.png) Im using "original-NachoSpigot"
> 
> you should use the -remapped version so you don't get errors due to missing methods

I believe it should be NachoSpigot.jar since that one is shaded

**Comment by Elierrr** [comment] 2022-03-03 20:54
> > ![image](https://user-images.githubusercontent.com/89429493/156474696-527b5bea-543b-4e01-b76d-3a7a002f1725.png) Im using "original-NachoSpigot"
> 
> you should use the -remapped version so you don't get errors due to missing methods

I believe it should be NachoSpigot.jar since it’s shaded

**Comment by Fumio-26** [comment] 2022-03-03 23:38
thank you guys
