### ISSUE TITLE
Operators do not persist

### ISSUE THREAD

**Issue by ceezuns** [CobbleSword/NachoSpigot#5] opened 2020-08-18 22:51 UTC
Hey!

It seem's like operators do not persist over restarts due to [Nacho-0033](https://github.com/CobbleSword/NachoSpigot/commit/b2dca118a023f889139823377f8321ddab345a84)

Thanks

**Comment by Lmmb74** [comment] 2020-12-28 00:01
Can confirm, still happening on latest build

**Comment by CyberFlameGO** [comment] 2021-04-24 13:20
No patches have been documented, I assume this still is an issue

**Comment by Lucaskyy** [comment] 2021-04-25 00:52
This is not a bug, but an (mostly unwanted) feature from NachoSpigot. This has been reverted and is disabled by default.

Operators do persistent in the current commit.

**Closing.**

**Closed** 2021-04-25 00:52 UTC
