### ISSUE TITLE
Fireball explosions wrong knockback

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#39] opened 2021-05-05 19:39 UTC
When you charge fireball in front of yourself and it explodes, it will knock you to the front, not from the explosion's location.

**Comment by Lucaskyy** [comment] 2021-05-06 08:14
Does this only happen when using NachoSpigot or does it also happen in other forks like TacoSpigot?

**Comment by andreasdc** [comment] 2021-05-06 18:06
@Lucaskyy I can't tell.

**Comment by LewUwU** [comment] 2021-05-06 18:07
Try please

**Comment by Lucaskyy** [comment] 2021-05-06 18:14
With this we can check if the issue is something done by us which makes it easier to find the issue.

**Comment by andreasdc** [comment] 2021-05-06 18:16
@Lucaskyy well it can be problematic to test with another fork, but I can try with original explosion class.

**Comment by andreasdc** [comment] 2021-05-08 13:20
@Lucaskyy I didn't check yet.

**Comment by Workinq** [comment] 2021-05-10 15:53
> Any success yet? @andreasdc

The same behaviour occurs with regular TacoSpigot, I don't think this is an issue on your part.

**Comment by Lucaskyy** [comment] 2021-05-11 01:53
Alright then, closing this issue for now. Might reopen it sometime.

**Closed by Lucaskyy** 2021-05-11 01:53 UTC

**Comment by andreasdc** [comment] 2021-05-16 02:09
@Lucaskyy it's the same with tnt.
