### ISSUE TITLE
Sometimes players cannot join on higher versions when using ViaVersion

### ISSUE THREAD

**Issue by kamber5** [CobbleSword/NachoSpigot#94] opened 2021-07-02 14:29 UTC
Hi

Here is the link where i explained a issue for ViaVersion: https://github.com/ViaVersion/ViaVersion/issues/2593

Seems NachoSpigot is not allowing players to join with 1.13.2, 1.16.4/5 and 1.17 to our 1.8 server even if the versions are allowed in ViaVersion plugin.

**Comment by crafter23456** [comment] 2021-07-02 14:41
It works, use latest from https://ci.viaversion.com/job/ViaVersion/lastStableBuild/
and drop it into the plugins folder of nacho. should work.
Viaversion on bungeecord does weird things.

**Comment by kamber5** [comment] 2021-07-02 16:05
Yes we have BungeeCord but we dont use ViaVersion plugin for BungeeCord and yes we are already on the latest version. There are moments when it work and there are moments when its not allowing players to join

**Comment by kamber5** [comment] 2021-07-04 13:13
Bump

**Comment by kamber5** [comment] 2021-07-04 13:13
Bump

**Comment by LewUwU** [comment] 2021-07-05 02:36
The unique fix that i can think is reverting the netty update

**Comment by baticag** [comment] 2021-07-06 15:05
> The unique fix that i can think is reverting the netty update

Is that possible? Can you do that please?

**Comment by poohzaza166** [comment] 2021-07-13 12:37
> Hi
> 
> Here is the link where i explained a issue for ViaVersion: [ViaVersion/ViaVersion#2593](https://github.com/ViaVersion/ViaVersion/issues/2593)
> 
> Seems NachoSpigot is not allowing players to join with 1.13.2, 1.16.4/5 and 1.17 to our 1.8 server even if the versions are allowed in ViaVersion plugin.

what is your java version

**Comment by Lucaskyy** [comment] 2021-07-15 12:12
This project has been abandoned for some time now, use something else. IonSpigot looks fine.

**Comment by wellnesscookie** [comment] 2021-07-15 12:40
Lovely. That's not the reason to close the issues, because they still persist.
Maybe someone would be interested in continuing the work. 

If disagreed, you should consider closing all of the issues with the reason you just provided, and not only the ones the people are encountering at the moment and asking for help.

**Comment by poohzaza166** [comment] 2021-07-15 12:42
i mean we could fork that some one can maintain it
but i am not that person i am not skill or knowledgeable enough

**Comment by Lucaskyy** [comment] 2021-07-15 12:45
There's no one that I know that wants to continue on this project. I just closed a couple of the issues, didn't feel like closing the others.

Like I said, the only solution you're going to get is to use something else. This is an open-source project, and you can't expect something to stay alive while I work on it in my free time for free. I don't have time for this anymore, and I don't like the Java language anymore. So I stopped with this project. It is, how it is.

**Comment by Lucaskyy** [comment] 2021-07-22 14:22
We'll need to take a look at this. Please share as much information as you can @kamber5 such as the error that occurs when that happens.

**Comment by Elierrr** [comment] 2021-09-26 12:05
I'm unable to reproduce this, try on the latest version.

**Comment by CyberFlameGO** [comment] 2021-09-26 12:52
The two deleted comments before https://github.com/CobbleSword/NachoSpigot/issues/94#issuecomment-884953746:
![image](https://user-images.githubusercontent.com/24910512/134808664-61fb145f-a7a0-4156-9ce9-8498dd15ffb7.png)
In future please hide comments instead of deleting them please! Deletion doesn't make sense in this context, though those two participants were indeed unhelpful and I understand the reasoning.

**Comment by CyberFlameGO** [comment] 2021-09-26 12:58
Extracted from https://github.com/CobbleSword/NachoSpigot/issues/94#issuecomment-879050432:
> > Hi
> > Here is the link where i explained a issue for ViaVersion: [ViaVersion/ViaVersion#2593](https://github.com/ViaVersion/ViaVersion/issues/2593)
> > Seems NachoSpigot is not allowing players to join with 1.13.2, 1.16.4/5 and 1.17 to our 1.8 server even if the versions are allowed in ViaVersion plugin.
> 
> what is your java version
`11.0.10`, running on Linux, plugin version `git-ViaVersion-4.0.1-SNAPSHOT:622ea916`

**Comment by refractored** [comment] 2021-11-15 18:32
Can this be closed now?

**Comment by kamber5** [comment] 2021-11-15 18:35
Yes

**Closed** 2021-11-15 19:33 UTC
